ToyStore/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using ToyStore.Areas.Access.Providers;
using ToyStore.Models;

namespace ToyStore.Controllers
{
    public class HomeController : Controller
    {

        private ToyStoreContext db = new ToyStoreContext();

        // GET: Home
        public ActionResult Index(int? idcategorie)
        {
            string str;
            IQueryable<TProduct> tProducts;

            if (idcategorie == null)
            {
                tProducts = db.TProducts
                    .Include(t => t.TCategorie)
                    .Include(t => t.TSubcategory);
            }
            else
            {
                tProducts = db.TProducts
                      .Where(t => t.TCategorie.idCategorie == idcategorie)
                      .Include(t => t.TCategorie)
                      .Include(t => t.TSubcategory);
            }


            foreach (var product in tProducts)
            {
                str = product.Description;
                if (str != null && str.Length > 20)
                    str = str.Substring(0, 40) + "...";
                product.SmallDescription = str;
            }
            return View(tProducts.ToList());
        }

        // GET: Home/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TProduct tProduct = db.TProducts.Find(id);
            if (tProduct == null)
            {
                return HttpNotFound();
            }
            return View(tProduct);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }


        [Authorize(Roles = "admin")]
        public ActionResult About()
        {
            ViewBag.Massage = "Ты вошол";
            return View();
        }
    }
}

ToyStore/Controllers/PurchasesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ToyStore.Models;

namespace ToyStore.Controllers
{
    public class PurchasesController : Controller
    {
        private ToyStoreContext db = new ToyStoreContext();

        [Authorize(Roles = "user, admin")]
        public ActionResult Purchase(TOrder order)
        {
            order.C_idBuyer = int.Parse(HttpContext.Request.Cookies["idBuyer"].Value);
            order.Date = DateTime.Now;
            
            db.TOrders.Add(order);
            db.SaveChanges();

            return Redirect("/Home/index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ToyStore/Views/Home/About.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>About</title>
</head>
<body>
    <div> 
        <h2>@ViewBag.Massage</h2>
    </div>
</body>
</html>

ToyStore/Views/Home/Details.cshtml
@model ToyStore.Models.TProduct

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Детально</title>
</head>
<body>
    <div>
        <h4>Товар</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.TCategorie.Category)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.TCategorie.Category)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.TSubcategory.Subcategory)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.TSubcategory.Subcategory)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Price)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Price)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Description)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Description)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Picture)
            </dt>
    
            <dd>
                @Html.Raw("<img style='width:80px; height:60px;' src=\"data:image/jpeg;base64,"
                                + Convert.ToBase64String(Model.Picture) + "\" />")
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Manufacturer)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Manufacturer)
            </dd>
    
        </dl>
    </div>
    <p>
        @Html.ActionLink("Вернутся обратно", "Index")
       

      
    </p>

@using (Html.BeginForm("Purchase", "Purchases"))
{
    <input type="hidden" name="C_idProduct" value="@Model.idProduct">
    <label>Выберите количество: </label>
    <input type="number" size="3" name="Quantity" min="1" max="1000" value="1">

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Купить" class="btn btn-default" />
        </div>
    </div>
}

</body>
</html>

ToyStore/Views/Home/Index.cshtml
@model IEnumerable<ToyStore.Models.TProduct>

@{
    Layout = null;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.TCategorie.Category)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TSubcategory.Subcategory)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Picture)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Manufacturer)
            </th>
            <th></th>
        </tr>
    
    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.TCategorie.Category)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TSubcategory.Subcategory)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SmallDescription)
            </td>
            <td>
                @Html.Raw("<img style='width:80px; height:60px;' src=\"data:image/jpeg;base64,"
                                + Convert.ToBase64String(item.Picture) + "\" />")
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Manufacturer)
            </td>
            <td>
                @Html.ActionLink("Выбрать", "Details", new { id=item.idProduct })
            </td>
        </tr>
    }
    
    </table>
</body>
</html>