ToyStore/Controllers/HeaderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ToyStore.Areas.Access.Providers;
using ToyStore.Models;

namespace ToyStore.Controllers
{
    public class HeaderController : Controller
    {
        private ToyStoreContext db = new ToyStoreContext();
        // GET: Header
        public ActionResult HeaderList()
        {
            string[] role;

            CustomRoleProvider userRole = new CustomRoleProvider();
            role = userRole.GetRolesForUser(User.Identity.Name);

            if (role.Length != 0 && "admin" == role[0])
                ViewBag.onAdmin = true;
            else
                ViewBag.onAdmin = false;

            var list = db.TCategories.ToList();

            return PartialView("_HeaderList", list);
        }


        public ActionResult ShowUser()
        {
            string result = "Вы не авторизованы";
            if (User.Identity.IsAuthenticated)
            {
                result = "Ваш логин: " + User.Identity.Name;
            }
            ViewBag.ActionResult = result;
            return PartialView("_ShowUser");
        }

        public ActionResult LogOut()
        {
            if (User.Identity.IsAuthenticated)

                ViewBag.LogOut = true;
            else
                ViewBag.LogOut = false;

            return PartialView("_LogOut");
        }
    }
}

ToyStore/Controllers/TOrdersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ToyStore.Models;

namespace ToyStore.Controllers
{
    public class TOrdersController : Controller
    {
        private ToyStoreContext db = new ToyStoreContext();

        // GET: TOrders
        [Authorize(Roles = "user, admin")]
        public ActionResult Index()
        {
          
            List<decimal> totalAmount = new List<decimal>();
            decimal result = 0;

            var id = int.Parse(HttpContext.Request.Cookies["idBuyer"].Value);
            var tOrders = db.TOrders.Where(t => t.TBuyer.idBuyer == id);
                
                
            
            
            /*.Include(t => t.TBuyer).Include(t => t.TProduct)*/;
            foreach (var order in tOrders)
            {
                
                order.Amount = order.TProduct.Price * order.Quantity;
                
                totalAmount.Add(order.Amount);
                //a.amo = a.TProduct.Price * (int)a.Аmount;
            }
            foreach(var amount in totalAmount)
            {
                
                result += amount; 
            }
            ViewBag.totalAmount = result;
            return View(tOrders.ToList());
        }

        // GET: TOrders/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TOrder tOrder = db.TOrders.Find(id);
            if (tOrder == null)
            {
                return HttpNotFound();
            }
            return View(tOrder);
        }

        // POST: TOrders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            TOrder tOrder = db.TOrders.Find(id);
            db.TOrders.Remove(tOrder);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ToyStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>

    <title>@ViewBag.Title – магазин</title>

    <link href="~/Content/Site.css" rel="stylesheet" />
</head>
<body>
   
<div class="header">
    <pre>Header Header Header Header Header Header Header Header
      Header Header Header Header Header Header Header Header
      Header Header Header Header Header Header Header Header
      Header Header Header Header Header Header Header Header
</pre>
    <div class="menu-right">
        @Html.Action("ShowUser", "Header")<br />
        @Html.Action("LogOut", "Header")<br />
        @Html.ActionLink("Регистрация", "Register", "Access/Account")<br />
        @Html.ActionLink("Корзина", "Index", "TOrders")<br />
    </div>
 
</div>
    

            @Html.Action("HeaderList", "Header")
           
    
   

    <hr />

    @RenderBody()
    <hr />
<pre>Footer Footer Footer Footer Footer Footer Footer Footer
    Footer Footer Footer Footer Footer Footer Footer Footer
    Footer Footer Footer Footer Footer Footer Footer Footer
    Footer Footer Footer Footer Footer Footer Footer Footer
    Footer Footer Footer Footer Footer Footer Footer Footer
    Footer Footer Footer Footer Footer Footer Footer Footer
    Footer Footer Footer Footer Footer Footer Footer Footer
</pre>

</body>
</html>